/* Autogenerated file, do not edit manually */
package chat.nexus.rpc.types;

public class ProviderInfo {
  public String beforeLoginHint;
  /** Unique ID, corresponding to provider database filename. */
  public String id;
  public String overviewPage;
  public Integer status;
}